name: Codecov

on:
  push:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      - name: Build
        run: nix develop .#codecov -c cargo build --release
      - name: Test
        run: nix develop .#codecov -c cargo test --all-features --no-fail-fast --tests
      - name: Install grcov
        run: nix develop .#codecov -c cargo install grcov
      - name: Generate coverage
        run: nix develop .#codecov -c grcov . --binary-path target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.lcov
          flags: rust
          # TODO: set true when CODECOV_TOKEN is set
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
