name: Tests

on:
  push:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      - name: Build & test
        run: nix develop .#stable -c cargo test --workspace --all-features --no-fail-fast --tests
  wasm-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      - name: Test in headless Chrome
        run: nix develop .#wasm -c wasm-pack test --headless --chrome
